t rebase --abort git rebase --abort it rebase --abort
git rebase --abort

odano widok Fabryki Portali

	#	pages/factory/index.tsx

directorr directory
fatal: pathspec 'pages/factory/indexgit add
pages/factory/index.tsxdexgit add pages/factory/index.tst>x
t>
>> C:\Users\czarn\Desktop\allfabet> git add pages/factory/index.tsxS
C:\Users\czarn\Desktop\allfabePS C:\Users\czarn\Desktop\allfabet> git
commit -m "Dodano widok Fabryki Portali"
>>
[main 87fc96e] Dodano widok Fabryki Portali
 1 file changed, 8 insertions(+)
  create mode 100644 pages/factory/index.tsx
  PS C:\Users\czarn\Desktop\allfabet> git push
  >>
  To https://github.com/czarnecki07-gif/allfabet-app.git
   ! [rejected]        main -> main (fetch first)
   error: failed to push some refs to
   'https://github.com/czarnecki07-gif/allfabet-app.git'
   hint: Updates were rejected because the remote contains work that
   you do not
   hint: have locally. This is usualushing to
   hint: the same ref. If you want to integrate the remote changes, use
   hint: 'git pull' before pushing again.
   hint: See the 'Note about fast-forwards' in 'git push --help' for
   details.
   PS C:\Users\czarn\Desktop\allfabet> git pull origin main --rebase
   >>
   remote: Enumerating objects: 12,
   done.
   remote: Counting objects:   8% (1remote: Counting objects:  16%
   (2remote: Counting objects:  25% (3remote: Counting objects:  33%
   (4remote: Counting objects:  41% (5remote: Counting objects:  50%
   (6remote: Counting objects:  58% (7remote: Counting objects:  66%
   (8remote: Counting objects:  75% (9remote: Counting objects:  83%
   (1remote: Counting objects:  91% (1remote: Counting objects: 100%
   (1remote: Counting objects: 100% (12/12), done.
   remote: Compressing objects:  14%remote: Compressing objects:
   28%remote: Compressing objects:  42%remote: Compressing objects:
   57%remote: Compressing objects:  71%remote: Compressing objects:
   85%remote: Compressing objects: 100%remote: Compressing objects: 100%
   (7/7), done.
   remote: Total 10 (delta 2), reused 0 (delta 0), pack-reused 0 (from
   0)
   Unpacking objects: 100% (10/10),
   2.25 KiB | 25.00 KiB/s, done.
   From https://github.com/czarnecki07-gif/allfabet-app
    * branch            main       -> FETCH_HEAD
       fba882c..0d3b150  main       -> origin/main
       Auto-merging pages/factory/index.tsx
       CONFLICT (add/add): Merge conflict in pages/factory/index.tsx
       error: could not apply 87fc96e... Dodano widok Fabryki Portali
       hint: Resolve all conflicts manually, mark them as resolved with
       hint: "git add/rm <conflicted_files>", then run "git rebase
       --continue".
       ommit: run "git rebase --skip".
       hint: To abort and get back to the state before "git rebase", run
       "git rebase --abort".
       hint: Disable this message with "git config set
       advice.mergeConflict false"
       Could not apply 87fc96e... # Dodano widok Fabryki Portali
       PS C:\Users\czarn\Desktop\allfabet> git push
       fatal: You are not currently on a branch.
       To push the history leading to the current (detached HEAD)
       state now, use

           git push origin HEAD:<name-of-remote-branch>

	   PS C:\Users\czarn\Desktop\allfabet> git status
	   >>
	   interactive rebase in progress; onto 0d3b150
	   Last command done (1 command done):
	      pick 87fc96e # Dodano widok Fabryki Portali
	      No commands remaining.
	      You are currently rebasing branch 'main' on '0d3b150'.
	        (fix conflicts and then run "git rebase --continue")
		  (use "git rebase --skip" to skip this patch)
		    (use "git rebase --abort" to check out the original
		    branch)

		    Unmerged paths:
		    e>..." to unstage)
		      (use "git add <file>..." to mar        both added:
		      pages/fat rebase --abort
		      git rebase --abort
		      t rebase --abort
		      git rebase --abort
		      t rebase --abort
		      git rebase --abort
		      it rebase --abort

		      git rebase --abort
		      <[unix] (21:40 10/01/2026)1,1 Topgit rebase
		      --abort

		      Dodano widok Fabryki Portali

		      # Conflicts:
		      <[unix] (21:40 10/01/2026)7,1 22nnPlease enter the
		      commit message for your changes. Lines starting